# nixpacks.toml (Final Diagnostic Version)

providers = ["node"]

[phases.install]
cmds = [
  "echo '--- STEP 1: Listing files in the current directory ---'",
  "ls -la",
  "echo '--- STEP 2: Installing dependencies ---'",
  "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"