# nixpacks.toml (Final Version)

providers = ["node"]

[phases.install]
cmds = ["npm install", "(cd shruggbot-ui && npm install)"]

[phases.build]
cmds = ["cd shruggbot-ui && npm run build"]

[start]
cmd = "npm start"